use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'yudexiang_Example' do
  pod 'yudexiang', :path => '../'

  target 'yudexiang_Tests' do
    inherit! :search_paths

    
  end
end
