use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/dgaf/yudexiang.git'


platform :ios, '8.0'

target 'yudexiang_Example' do
  pod 'yudexiang', :path => '../'

  target 'yudexiang_Tests' do
    inherit! :search_paths

    
  end
end
